# Generated by Django 4.2.13 on 2024-06-23 00:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('litter_app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='rewards',
            name='user',
        ),
        migrations.RemoveField(
            model_name='trashpost',
            name='user',
        ),
        migrations.AddField(
            model_name='rewards',
            name='user_id',
            field=models.CharField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='trashpost',
            name='user_id',
            field=models.CharField(default=1),
            preserve_default=False,
        ),
    ]
